#
# default theme for JamMt
#

# color of the 'y' axis
ChartFgCol: 255, 0, 0, 255

# background color of the chart
ChartBgCol: 230, 230, 230, 255

# color of the 'y2' axis
ChartFg2Col: 0, 200, 0, 255

# color of grid
GridCol: 30, 30, 30, 255

# background color of the info boxes
InfoboxBgCol: 250, 250, 250, 255

# foreground color of the info boxes
InfoboxFgCol: 40, 40, 40, 255

# y coordinates
handle_y = -0.4
lens_y = 0.0
substrate_y = 0.0
beam-analyzer_y = 0.0
clipping_y = 0.0
text-label_y = 0.0
info-box_y = 0.5

# components heights
handle_h = 0.1
lens_h = 0.4
substrate_h = 0.4
beam-analyzer_h = 0.8
clipping_h = 0.2
text-label_h = 0.8
info-box_h = 0.4

